### ISSUE TITLE
Bulk Instrument Search By Symbol

### ISSUE THREAD

**Issue by bvallelunga** [sanko/Robinhood#1]
I would really appreciate it if anyone knows how to do a bulk instrument search by a list of symbols.

**Comment by wlynnInhanceTechnology** [comment]
yes it would be great,

**Comment by sanko** [comment]
Are you trying to get the full fledged instrument data (tradeability, name, market, etc.) or just the id which can be used to make orders, etc.? If you're just looking for  ids, try using the `/prices/` endpoint. I haven't documented it yet outside of #5 yet.

**Comment by bvallelunga** [comment]
Yea I am trying to get fully fledged instrument data but thank you for letting me know about `prices` endpoint.
