### ISSUE TITLE
Long range historical data

### ISSUE THREAD

**Issue by 01000101** [sanko/Robinhood#10]
Hey, reading through your notes on getting history quotes, I see there's "interval" and "span". I don't see how to specify a range of dates or even a chunk of time such as "get 1yr of weekly/monthly data" or "get all time history" like in the app. Any thoughts?

**Comment by sanko** [comment]
Haven't documented historical quotes retrieval here yet but I have in my perl module. The possible intervals are "5minute", "10minute", "day", or "week" and the span must be "day", "week", "year", or "5year".

There are limits though, for example, it'll return an error if you try getting a year of data at 5 minute intervals.

**Comment by 01000101** [comment]
Fantastic, thank you! I'll report any issues or new findings when I run a
test on that today.

**Comment by 01000101** [comment]
I'm still working with the historical data piece (it will eventually be the input for a historical data graph). I did add the project to Github, even in its early stage. Might be of use to someone. https://github.com/01000101/robinhood-joscor-ui/

**Comment by sanko** [comment]
(When I get to it,) I'd love to add a section in the README.md for open projects that use/contribute to these docs. Thanks for the link!

**Comment by gliptak** [comment]
Would you have details on how far back historical data can be queried? Thanks

https://github.com/sanko/Robinhood/blob/master/Quote.md

**Comment by sanko** [comment]
Reading the docs and comments to this very issue, take a guess.
