### ISSUE TITLE
Market Buy Failures

### ISSUE THREAD

**Issue by LeastOne** [sanko/Robinhood#11]
On Friday January 13th I was able to successfully issue good-for-day market orders to both buy and sell. However, this week I've only been able to successfully issue good-for-day market orders to sell only. For example, when issuing the following request:

```
curl -v https://api.robinhood.com/orders/ \
   -H "Accept: application/json" \
   -H "Authorization: Token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
   -d account=https://api.robinhood.com/accounts/xxxxxxxx/ \
   -d instrument=https://api.robinhood.com/instruments/1671042c-5f2c-4fee-bb2f-0e4be2bcf24e/ \
   -d symbol=AMAG
   -d type=market \
   -d time_in_force=gfd \
   -d trigger=immediate \
   -d quantity=4 \
   -d side=buy
```

I get the following response:

```
{"non_field_errors":["Market buy order requested, but no price provided."]}
```

This seems a most unusual error given its a market order and the price isn't required when the side is sell.

If I try to provide an empty price I get the same response. If I try to provide a null price I get this response:

```
{"price":["A valid number is required."]}
```

If I try to provide a price of zero I receive the following (not surprising):

```
{"price":["Ensure this value is greater than 0."]}
```

If I first quote the symbol and get the last-trade-price and provide that as the price the order appears to get converted to a limit order. Whereby if the price remains the same or has dropped in between the quote and the order it is fulfilled immediately but otherwise the order remains unfulfilled until the price increases to trigger the order.

I get the same results regardless of whether I set time-in-force to 'gfd' or 'gtc'. If I try 'ioc' or 'fok' I get the following response:

```
{"time_in_force":["Invalid time in force ioc."]}
```

If I trade through the app it is able to successfully issue a market order immediately. So it seems I'm missing some parameters or the app uses a different end-point.

Do you have any insight to offer that might explain my results? Do you have any suggestions as to how I can get a simple market order buy to execute successfully?

**Comment by sanko** [comment]
Everything sounds right (even if it is weird to send a price on a market order) except the time in force response... I'll try it after-hours and get back to you. Would be terrible to lose even more API functionality.

**Comment by brandon-hall-physio-control** [comment]
Thanks for the response, really appreciate your input.

When you say ...

> Everything sounds right (even if it is weird to send a price on a market order)

Do you mean that you think its normal to issue an immediate market order buy that gets treated like a limit order? If so, I'm confused by this. I'm able to issue an immediate market order sell that gets executed at the best available market price. I expect that the same should be possible when buying.

As I mentioned, the primary obstacle here is if my market order gets converted to a limit order and the price increases my order remains pending perhaps indefinitely.

Again, thanks for your response!

**Comment by LeastOne** [comment]
Thanks for the response, really appreciate your input.

When you say ...

> Everything sounds right (even if it is weird to send a price on a market order)

Do you mean that you think its normal to issue an immediate market order buy that gets treated like a limit order? If so, I'm confused by this. I'm able to issue an immediate market order sell that gets executed at the best available market price. I expect that the same should be possible when buying.

As I mentioned, the primary obstacle here is if my market order gets converted to a limit order and the price increases my order remains pending perhaps indefinitely.

Again, thanks for your response!

**Comment by sanko** [comment]
It's normal for the API server to require a price even when it's a market order. I never understood why...

It is strange that the type is being ignored though.

**Comment by ajferrick** [comment]
@LeastOne Maybe try adding a price to the market order API call to see if it executes? To add a data point to this: when I try to call the API with a (close but ultimately bogus) price I get `201 Accepted` but never see the order actually execute during open market hours.

**Comment by LeastOne** [comment]
@ajferrick, thanks for contributing. Concerning the following suggestion ...

> Maybe try adding a price to the market order API call to see if it executes?

This is exactly what I first tried. The following is from my original post above ...

> If I first quote the symbol and get the last-trade-price and provide that as the price the order appears to get converted to a limit order.

So yes, if I submit a price the order sometimes fulfills immediately, but sometimes it takes a minute or more to fill and sometimes it doesn't fill at all. As I mention in my original post, this leads me to believe its being treated like a limit order and not a market order.

Today I tried a new approach. For the security I wish to buy I'm first getting a quote and instead of using the last-trade-price I'm using the ask-price. The result today was that all three of the purchases I made executed immediately. However, this could be complete coincidence. As I said, previously some of my orders would execute immediately. I'll need to see how it performs over the remainder of the week before I draw any conclusions.

Additionally, in the event the order does not execute immediately I'm continuing to check it for one minute. If the order doesn't execute in that time I then move on. This is the best alternative I've come up with for the time being.

**Comment by sanko** [comment]
What do the orders look like when you 1) look in the app and 2) fetch the order again with the correct endpoint (`https://api.robinhood.com/orders/{order_id}/`)?

**Comment by LeastOne** [comment]
@sanko 

1) The app shows the pending order but unfortunately doesn't indicate whether or not its a market order. However, once the order clears it does correctly show it was a market order.

2) When I fetch the unfulfilled order from the API it does show it to be an immediate market order. Below is an example pending order from Friday. It did eventually execute, but it took several minutes.

```
{
  "updated_at": "2017-01-20T14:40:04.017757Z",
  "ref_id": null,
  "time_in_force": "gfd",
  "fees": "0.00",
  "cancel": "https://api.robinhood.com/orders/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/cancel/",
  "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "cumulative_quantity": "0.00000",
  "stop_price": null,
  "reject_reason": null,
  "instrument": "https://api.robinhood.com/instruments/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/",
  "state": "confirmed",
  "trigger": "immediate",
  "type": "market",
  "last_transaction_at": "2017-01-20T14:40:03.879000Z",
  "price": "14.90000000",
  "executions": [],
  "extended_hours": false,
  "account": "https://api.robinhood.com/accounts/xxxxxxxx/",
  "url": "https://api.robinhood.com/orders/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/",
  "created_at": "2017-01-20T14:40:03.378102Z",
  "side": "buy",
  "position": "https://api.robinhood.com/positions/xxxxxxxx/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/",
  "average_price": null,
  "quantity": "7.00000"
}
```

I've wondered if its a volume issue but it seems quite unlikely given the few shares I'm trying to trade. Also, I've only ever seen the order hang when I call the API directly. Whenever I've traded from the app I've never observed an order taking more than a few mere seconds to execute. If anyone has experienced the app taking a minute or more to fulfill an immediate market order I would be curious to know that.

**Comment by bchantech** [comment]
@LeastOne From my own tests, when placing a market buy order using the app it sets `price` to 5% above the last trading price (eg. if the stock last traded at 50, the price will show as 52.5 on the API, even though the order can execute below that). This isn't done automatically for you when using the API to place market orders, so the price needs to be set high enough for the order to fill.

I'm pretty sure they are treated as limit orders, since I placed a market buy order with the API during pre-market (with `extended_hours=true`) and it immediately filled.

**Comment by sanko** [comment]
That's in line with the official docs (https://support.robinhood.com/hc/en-us/articles/208650386-Order-Types) which state that "Market buy orders are adjusted to limit orders collared up to 5%."

**Comment by LeastOne** [comment]
Thanks @sanko, this is exactly the answer I was looking for.

Since your last message I've been able to confirm exactly that behavior. Collaring up the ask price was the piece I was missing!

There are still a few trades that take a minute or so to execute but its functioning quite sufficiently for my purposes at the moment.

**Comment by llinsky** [comment]
Regarding this issue: The Robinhood API clearly distinguishes between valid options (that were once supported in this manner) and invalid options. Example:

`rbx.place_order(instr[0], 1, 12.12, 'buy', 'immediate', 'limit', 'ioc')
Out[28]: <Response [400]>

_.text
Out[29]: u'{"time_in_force":["Invalid time in force ioc."]}'

rbx.place_order(instr[0], 1, 12.12, 'buy', 'immediate', 'limit', 'dsf')
Out[30]: <Response [400]>

_.text
Out[31]: u'{"time_in_force":["\\"dsf\\" is not a valid choice."]}'`

Perhaps there is a different combination of parameters that are now needed to support these options?
