### ISSUE TITLE
Login when MFA is enabled

### ISSUE THREAD

**Issue by tolidano** [sanko/Robinhood#12]
When MFA is enabled, login will return:
`{"mfa_type":"sms","mfa_required":true}`
And then I get a text message on my phone.

I presume some OTHER URL is needed to take the SMS code.
it would be great to document this (although I'll just turn MFA off for now).

**Comment by he-zhe** [comment]
#14 Try this?

**Comment by sanko** [comment]
I'd rather not turn multi-factor on so if @tolidano tests and verifies the docs are correct, I'll accept pr #14.

**Comment by tolidano** [comment]
I'll turn my MFA back on and modify my stuff to see if this works and report back here, before Sunday.

**Comment by tolidano** [comment]
I can confirm this works as described. The token is returned when the mfa_code parameter is set to the code sent by SMS to the phone number on the account. Please merge that in. Thanks for figuring that out.

**Comment by sanko** [comment]
Thank you both!
