### ISSUE TITLE
Order limit due to margin restraints

### ISSUE THREAD

**Issue by somacoder** [sanko/Robinhood#13]
Under a normal account, you are often prevented from the max number of shares you can purchase with your "buying power" due to RobinHood requiring a particular "buffer/margin" of error in case the market shifts by the time the buy is executed. Is there any way to get a hold of this buffer/margin before the buy is executed? That way you can prevent having the order fail for being over the limits of said buffer/margin.

**Comment by sanko** [comment]
Use limits. I imagine they just add 5% (their market order collar) to the last sell price.
