### ISSUE TITLE
Order state as uncomfirmed?

### ISSUE THREAD

**Issue by pmiller624** [sanko/Robinhood#18]
When would an order's state be set as uncomfirmed? I have an order that's been filled but the state is still coming back as unconfirmed.

**Comment by AdamBrodzinski** [comment]
@pmiller624 i'm getting this too, in my orders history it will show as unconfirmed for a short period of time and will eventually switch to 'filled' when queried later (even though it's updating every second). Did you find out any more information on this?

**Comment by pmiller624** [comment]
@AdamBrodzinski I wasn't able to find any additional information on the unconfirmed status. In my case it was safe enough to assume unconfirmed was filled.

**Comment by AdamBrodzinski** [comment]
@pmiller624 thanks for the feedback! 👍

**Comment by rclai** [comment]
Is this still happening to you guys? I tested an order and it went from unconfirmed to confirmed or queued.
