### ISSUE TITLE
Instruments now requires authentication

### ISSUE THREAD

**Issue by tolidano** [sanko/Robinhood#19]
Various calls to /instruments/ now fail unless the auth token is passed. The "Authentication" column should be switched from "No" to "Yes" for these use cases.

**Comment by sanko** [comment]
Are you sure? https://api.robinhood.com/instruments/66ec1551-e033-4f9a-a46f-2b73aa529977/ still works fine just hitting it with chrome.

**Comment by tolidano** [comment]
I will have to check which use case trips it but when I attempted an instrument call (perhaps by symbol), it gave me the error. 

- Shawn (iPhone)

**Comment by sanko** [comment]
Any updates on this?

**Comment by roblav96** [comment]
@sanko I've never had this happen before and I've been playing around with this API for a while.

**Comment by sanko** [comment]
Yeah. @tolidano, if you ever track this down, reopen this issue with more info.
