### ISSUE TITLE
Placing a stop-loss order for an existing order doesn't work.

### ISSUE THREAD

**Issue by wlynnInhanceTechnology** [sanko/Robinhood#2]
placing a stop-loss order for an existing order doesn't work.
Stock was already purchased with no stop-loss or limit-sell orders in place.

Server responds with bad request, when using the following parameters.
 RequestParams requestParameters = new RequestParams();
        requestParameters.put("account",account);       //url
        requestParameters.put("instrument",instrument);
        requestParameters.put("symbol",symbol);
        requestParameters.put("type","limit");
        requestParameters.put("time_in_force","gtc");
        requestParameters.put("trigger","stop");
        requestParameters.put("stop_price",stoplossPrice);
        requestParameters.put("quantity",quantity);
        requestParameters.put("side","sell");

**Comment by sanko** [comment]
You're trying to modify an order? Their API doesn't allow that. Cancel the original order first.

**Comment by wlynnInhanceTechnology** [comment]
sorry I'm not making it very clear, but here is a good example.
Lets say I have 4 shares of SBUX in my portfolio already.
and I want to send in a stop-loss order to sell 4 shares of SBUX for 20.00.
The API says I need the following, but its failing.
I'm following the steps from
https://github.com/sanko/Robinhood/blob/master/Order.md#place-an-order

RequestParams requestParameters = new RequestParams();
requestParameters.put("account",account); 
requestParameters.put("instrument","xyxblahblah");
requestParameters.put("symbol","SBUX");
requestParameters.put("type","limit");
requestParameters.put("time_in_force","gtc");
requestParameters.put("trigger","stop");
requestParameters.put("stop_price",20.00);
requestParameters.put("quantity",4);
requestParameters.put("side","sell");

**Comment by sanko** [comment]
Your text says stop-loss but your code is attempting to create a stop-limit order.

If you intend to create a stop-loss, try changing the 'type' to 'market'. The order will convert to a market sell when the stop price is met. If you're trying to create a stop-limit, you'll need to include a limit 'price'.

**Comment by wlynnInhanceTechnology** [comment]
thank you, that was it.
Would you be able to make a note about , needing the "type":"market", for stop-loss orders
in the documentation ?

**Comment by sanko** [comment]
Stop-loss orders are market orders by definition but... Fork it. Add non-intrusive links to Investopia
[[1](http://www.investopedia.com/articles/active-trading/091813/which-order-use-stoploss-or-stoplimit-orders.asp), [2](http://www.investopedia.com/terms/s/stop-lossorder.asp), [3](http://www.investopedia.com/terms/s/stop-limitorder.asp)]. Create a pull request.
