### ISSUE TITLE
Proper Parameters for Order Types

### ISSUE THREAD

**Issue by jdulb17** [sanko/Robinhood#23]
Hello, 

I am working on making limit and market orders, but I can't seem to match up the proper triggers & time_in_forces. I assumed a trigger of "on_close" with a time_in_force of "gfd" for a limit order, but I was told invalid trigger of "on_close" so I switched to "immediate". With market orders, I have a trigger of "immediate" with a time_in_force of "fok", but I get the error of "invalid time in force of fok". Before I begin making orders from my application, I want to verify that I have the proper trigger paired with the time_in_force so I correctly make market & limit orders. Thank you!

**Comment by drew-wallace** [comment]
If you have past orders you can take a look at those. I've only ever seen gfd and gtc for time_in_force. For trigger I've only seen immediate for limit and market, and stop for stop orders.
