### ISSUE TITLE
The amount you can use to buy stock?

### ISSUE THREAD

**Issue by illl48** [sanko/Robinhood#26]
First of all I'd like to say thank you to Sanko for this repo.

1. I'd like to know what is the amount i should check before buying stocks?
    (The type of my account is margin.)
    The account.buying_power doesn't match the buying power showed on the app.
    ~~account.cash or~~ account.margin_balances.unallocated_margin_cash seem have the correct number.
    Which one should i use? (and what if the type of my account is cash or havin robinhood gold?)

2.  Are these the right combinations of order types?

| Types          |type       | time_in_force |trigger        |
| -------------|--------- |----------------|-------------|
| MARKET     | market  | gfd                 |immediate  |
| LIMIT          | limit      |   gfd  or  gtc  |immediate  |
| STOP LOSS | market  |    gfd  or  gtc | stop|
| STOP LIMIT| limit      |   gfd  or  gtc   |stop |

3. whats the API for earnings reports?

Appreciate it.

**Comment by illl48** [comment]
i think the api for Create watchlist doesn't work anymore.

**Comment by sanko** [comment]
@illl48 Yeah, they started restricting that last fall.

**Comment by illl48** [comment]
@sanko Thanks for the response.
Another question, whats is {ids}  for reorderin watchlist ( POST /watchlists/$watchlistName/reorder/	{ids})
