### ISSUE TITLE
Missing \ in the logout spec

### ISSUE THREAD

**Issue by ZAYDEK** [sanko/Robinhood#27]
`curl "https://api.robinhood.com/api-token-logout/" \`
`  -H "Accept: application/json" \`
`  -H "Authorization: Token xoxo" \` <-
`  -d ""`

<3

**Comment by sanko** [comment]
You wanna make a little PR for this or...?

**Comment by zaydek** [comment]
What's a PR? Peer review?

**Comment by zaydek** [comment]
PULL REQUEST !
