### ISSUE TITLE
Earnings endpoint?

### ISSUE THREAD

**Issue by bcwik9** [sanko/Robinhood#29]
Has anyone been able to figure out how to query for earnings data via the API?

**Comment by bcwik9** [comment]
I see the `https://analytics.robinhood.com/experiments/earnings/` endpoint, and I'm a participant in that experiment, but I still haven't had any luck.

**Comment by sanko** [comment]
There are three ways to access data from a single endpoint. I need to add this and a lot more to the docs but I'm super busy recently.
    
  - `GET https://api.robinhood.com/marketdata/earnings/?range={X}day`
    Where `X` is an integer between 1 and 21. This returns *all* expected earnings within a number of calendar days. This will be huge if you're looking for more than a day or two. The apps never request or cache more than 7 days into the future.

  - `GET https://api.robinhood.com/marketdata/earnings/?instrument={url}`
    Where `URL` is a full instrument url. So, you would be requesting data like `https://api.robinhood.com/marketdata/earnings/?instrument=https://api.robinhood.com/instruments/50810c35-d215-4866-9758-0ada4ac79ffa/`

  -  `GET https://api.robinhood.com/marketdata/earnings/?symbol={symbol}`
    Where `symbol` is a plain ol' ticker symbol. This is probably the easiest way unless you have the instrument's data already.

Unfortunately, this endpoint does not support CSV for params like some other endpoints so you can only request data for one symbol or instrument at a time.

**Comment by sanko** [comment]
Oh, and they all work without being logged in. If you could leave this issue open for now, that'd be awesome. I'll forget to add it to the docs if it's closed.

**Comment by bcwik9** [comment]
Thanks for the response, this is great! Out of curiosity, how are you discovering these endpoints? I ran all around the API testing things, and even resorted to trying to read the traffic the phone app was generating (without success).

**Comment by roblav96** [comment]
@bcwik9 I tried doing the same with a network packet sniffer on a rooted android device but had no luck. If I were to guess, I'd say grab an `apk` binary and decompile it using [Apktool](https://github.com/iBotPeaches/Apktool).

**Comment by ibzx** [comment]
@roblav96 You can also install a custom root certificate and use a tool like BURP or MITMPROXY. The reason why the packet sniffer doesn't work is because its all over HTTPS. This will yield the decrypted HTTP packets.

**Comment by sanko** [comment]
@roblav96 @ibzx : is this what you're doing?

Sigh... why ya'll gotta make more work for people? 💢

**Comment by roblav96** [comment]
@sanko @ibzx https://gist.github.com/roblav96/d63352008d791480796947dabfd2cbd8 Shows all API methods known.

Also @sanko can you merge this earnings PRs? https://github.com/sanko/Robinhood/pulls

**Comment by sanko** [comment]
I very very very strongly suggest you stop using decompiled versions of their source. It puts you on the wrong side of a (as of now) very lenient and downright supportive group of devs and legal representatives.

I'm removing your comment because I'm not going to be responsible for helping distribute source code that is protected by copyright and sure to bring the attention of RH's General Counsel and their Head of Business Development (both of whom I've already been in contact with). I am acting within the bounds defined by them; tearing down their apps is outside of those bounds. Not to be overly dramatic but the sort of thing you posted and advised others to do can bring the sky down on our heads.

**Comment by ibzx** [comment]
Was this directed at me? Installing a custom root certificate on the iOS or Android platform and then performing an mitm proxy on the app does not decompile or alter the application in anyway and would yield all the API endpoints. 

On another note: I would love to know how/why the mitm proxy would cause more work? you seem particularly upset about expanding the known endpoints in that manner and if it does cause more work I will stop.

**Comment by sanko** [comment]
@ibzx I was so quick to take it down that I forgot to @ the right guy. :)
