### ISSUE TITLE
Get Portfolio Historicals

### ISSUE THREAD

**Issue by drew-wallace** [sanko/Robinhood#3]
I'm hitting the endpoint `https://api.robinhood.com/portfolios/historicals/$account_number?span=day&interval=5minute`
But I'm getting this back: a 401 with this: `{"detail":"Authentication credentials were not provided."}`

I checked my auth header token and it's fine. The other endpoints that need the token work.

Any thoughts? Thanks.

**Comment by sanko** [comment]
I can't duplicate this... is it still happening for you?

**Comment by drew-wallace** [comment]
It is. Can you send me the request you're making so I can compare it to mine?

**Comment by sanko** [comment]
Sure. Mine looks like...

```perl
# (
#   "GET",
#   "https://api.robinhood.com/portfolios/historicals/[8 char acct number redacted]/?span=day&interval=5minute",
#   {
#     headers => {
#       "Accept"                  => "*/*",
#       "Accept-Language"         => "en;q=1, fr;q=0.9, de;q=0.8, ja;q=0.7, nl;q=0.6, it;q=0.5",
#       "Authorization"           => "Token [40 char token redacted]",
#       "Content-Type"            => "application/x-www-form-urlencoded; charset=utf-8",
#       "User-Agent"              => "Robinhood/823 (iPhone; iOS 7.1.2; Scale/2.00)",
#       "X-Robinhood-API-Version" => "1.70.0",
#     },
#   },
# )
```

...and I get this in return:

```perl
# {
#   content  => "[equity_historicals, total_return, etc. redacted]",
#   headers  => {
#                 "allow" => "GET, HEAD, OPTIONS",
#                 "connection" => "keep-alive",
#                 "content-language" => "en-us",
#                 "content-type" => "application/json",
#                 "date" => "Wed, 13 Jul 2016 20:13:48 GMT",
#                 "server" => "nginx",
#                 "strict-transport-security" => "max-age=31536000",
#                 "transfer-encoding" => "chunked",
#                 "vary" => ["Accept-Encoding", "Accept-Language, Cookie"],
#                 "x-robinhood-api-version" => "1.92.3",
#               },
#   protocol => "HTTP/1.1",
#   reason   => "OK",
#   status   => 200,
#   success  => 1,
#   url      => "https://api.robinhood.com/portfolios/historicals/[8 char acct number redacted]/?span=day&interval=5minute",
# }
```

**Comment by drew-wallace** [comment]
You have a `$account_nubmer/?span=...` but I am missing the `/` before the query params. I'll try again when I get off work.

**Comment by sanko** [comment]
It should redirect (`301`) to the correct url with a trailing slash.

**Comment by drew-wallace** [comment]
Your headers have `"X-Robinhood-API-Version" : "1.70.0"` my version is `1.0.0`. That might be part of the problem. I also have: ```{"Accept-Encoding": "gzip, deflate", "Connection": "keep-alive"}``` But, I would hope that wouldn't cause issues.

**Comment by drew-wallace** [comment]
Turned out to be the `/` before the query params...

**Comment by sanko** [comment]
Weird. My client gets the redirect header instead of just failing. Guess we can close this one then.
