### ISSUE TITLE
Reorder positions param information

### ISSUE THREAD

**Issue by bcwik9** [sanko/Robinhood#30]
I'm looking to reorder my positions list, and see:
```
Reorder Positions				GET /positions/?ordering=$ordering
```
Any tips on how to format the `ordering` param?

**Comment by roblav96** [comment]
@bcwik9 Try calling it with a malformed parameter. It usually responds with the instructions.

**Comment by bcwik9** [comment]
I gave it a shot but didn't have any luck. All I get back are my list of positions.

**Comment by illl48** [comment]
POST https://api.robinhood.com/watchlists/Default/reorder/
body: uuids: instrumentID,  instrumentID      
this should work

**Comment by illl48** [comment]
have you tried GET /positions/?ordering=instrumentid,instrumentid,instrumentid,instrumentid.......

**Comment by bcwik9** [comment]
Thanks for the response, @illl48! I was able to get the portfolio ordering working.... now on to the watch list.

**Comment by quangkieu** [comment]
hi @roblav96, do you might share your sample api call on how to reorder watch list?

**Comment by roblav96** [comment]
@quangkieu 
```java
    @POST("/watchlists/{watchlistName}/reorder/")
    Observable<Void> reorderWatchlist(@Path("watchlistName") String str, @Body ReorderQuery reorderQuery);
```
I have not used this query before but this might give you a clue.

**Comment by bcwik9** [comment]
When authenticated, call `GET` with:
`https://api.robinhood.com/positions/?ordering=<comma separated instrument IDs>`

for example:
`https://api.robinhood.com/positions/?ordering=20,19,21,100`

**Comment by bcwik9** [comment]
and for watch list it's essentially the same, but with a `POST` instead of `GET`:
`https://api.robinhood.com/watchlists/<watchlist name>/reorder/`, and attach params to send with `uuids` as the param name (it's still just instrument IDs). so I call it like:
`"https://api.robinhood.com/watchlists/#{name}/reorder/", {uuids: "20,19,21,100"}`

**Comment by quangkieu** [comment]
@bcwik9 thank for the code sample
