### ISSUE TITLE
Question: delayed data

### ISSUE THREAD

**Issue by sagivo** [sanko/Robinhood#34]
I didn't find any info about how "real-time" the quotes are. is this info delayed? 
I say some people add `delayed=false` to some of the info. is that needed?

**Comment by MoBattah** [comment]
This is not an issue. 

RobinHood only passes delayed information (including quotes). All data can be delayed 20 minutes or longer as is written in the RobinHood Terms of Service.

**Comment by MoBattah** [comment]
@sanko Please close this issue.

**Comment by sagivo** [comment]
thanks @MoBattah i'm closing the issue. 
just to double check - you say that also the data in the actual API is delayed (not just the app)?

**Comment by sanko** [comment]
No one is allowed to give full, real time quote data for free. What you see as the 'price' in the apps is the last trade price which can be quoted for free. The spread is 15mins behind in accordance with the rules set out by the exchanges.

Live quote data can be pulled from the tape but that's one of the bits I'm not supposed to document.
