### ISSUE TITLE
Invalid time_in_force options

### ISSUE THREAD

**Issue by ihammerstrom** [sanko/Robinhood#37]
For time in force the following options are listed:
gfd, gtc, ioc, fok or opg
However, it appears that only:
gfd, gtc
actually work.

When using the following curl command (which is nearly copied/pasted from the order example which uses time_in_force=fok):
curl -v https://api.robinhood.com/orders/ \
   -H "Accept: application/json" \
   -H "Authorization: Token [my_token]" \
   -d account=https://api.robinhood.com/accounts/[my_acct]/ \
   -d instrument=https://api.robinhood.com/instruments/50810c35-d215-4866-9758-0ada4ac79ffa/ \
   -d symbol=MSFT \
   -d type=market \
   -d time_in_force=fok \
   -d trigger=immediate \
   -d quantity=1 \
   -d side=buy \
   -d price=70.00

I get the following error:
{"time_in_force":["Invalid time in force fok."]}
and with all caps FOK I get the error which would appear had I typed any other generic invalid value:
{"time_in_force":["\"FOK\" is not a valid choice."]}

There is at least a different handling of the "fok" time_in_force option from the error message given, but has anyone actually gotten specifically "fok" or any other non-(gfd, gtc)  time_in_force values to work?
I've also tried this using "ioc" which didn't work, I assume this doesn't work with the other non-(gfd, gtc) values as well.

**Comment by illl48** [comment]
| Types          |type       | time_in_force |trigger        |
| -------------|--------- |----------------|-------------|
| MARKET     | market  | gfd                 |immediate  |
| LIMIT          | limit      |   gfd  or  gtc  |immediate  |
| STOP LOSS | market  |    gfd  or  gtc | stop|
| STOP LIMIT| limit      |   gfd  or  gtc   |stop |

These are all the combinations I know work.

**Comment by NavnathKale** [comment]
Hi, I came across same observation recently. Not sure if there is specific combination to make it work..

**Comment by sanko** [comment]
Let's just go ahead and say FOK is no longer supported. It used to be but maybe isn't anymore. I haven't gotten around to testing it for this issue but if it's not working for you guys, that's good enough for me.
