### ISSUE TITLE
Making an Order

### ISSUE THREAD

**Issue by karl16** [sanko/Robinhood#38]
When I try and create an order using the API I get an HTTP Error 400: Bad Request. I am using python and here is my code

`valuesBuy = {"account": account, "instrument": instrument, "symbol": "XXII", "type": "market", "time_in_force": "gfd", "trigger": "immediate", "quantity": 1, "side": "buy"}

dataBuy = urlencode(valuesBuy).encode()

qBuy = Request("https://api.robinhood.com/orders/", dataBuy)

qBuy.add_header("Authorization", inputTok)

htmlBuy = urlopen(qBuy)

responseBuy = (htmlBuy.read())

print(responseBuy)`

Also I'm using python 3.6.1
Also I have tried putting quotes around the quantity value and still got the same error message

**Comment by sanko** [comment]
Can't tell but is that an HTTP POST?

**Comment by karl16** [comment]
Yes it is an HTTP POST. Urllib automatically makes it a post when a data variable is present. I also know that that part works because I was able to get an authorization token. I'm just wondering if the all the Values aren't included or something like that. If I leave out the data variable it will show me the recent orders so I know the Token is correct.

**Comment by illl48** [comment]
SEC's Tick Size Pilot Program?

**Comment by lynnwilliam** [comment]
That program is a joke !

**Comment by karl16** [comment]
I am still having the same problem I have tried setting the User-Agent but to no avail. I think the problem might be with sending a header and data but I am not sure. Also I am using urllib for python 3

**Comment by sanko** [comment]
@karl16 Maybe your project's requirements prevent it but if not, have you tried using one of the preexisting Python libs that will the API?

**Comment by karl16** [comment]
I have not tried one of the preexisting Python libs that use the API because I am trying to learn about using API's and want to be able to do more specialized things with the Robinhood API

**Comment by karl16** [comment]
I Figured out the problem. Even for a market order you must include the price parameter.
