### ISSUE TITLE
Ticker SB returns SBUX from Robinhood

### ISSUE THREAD

**Issue by Micah81** [sanko/Robinhood#39]
SB and SBUX is just one example. If the ticker has less than four letters, there's a chance of RH returning the wrong symbol.  Are there some placeholders we can use? 

I've pulled in the Bloomberg_Unique field from OpenFIGI, but so far I've been unable to pull the symbol from RH using the Bloomberg_Unique. This is probably only due to my inexperience because the /instruments/ endpoint does provide the Bloomberg_Unique field. 

Since I haven't seen anyone discussing this problem, the answer is probably really simple.

**Comment by sanko** [comment]
...which endpoint are you using?

**Comment by Micah81** [comment]
I'm using the instruments endpoint. Here is the code where the problem occurs. It pulls from a file formatted with SYMBOL,QTY on each line, like: 
SB,3
NFLX,5

The output is: 

SBUX != SB
NFLX == NFLX

```
from Robinhood import Robinhood
print("-- Account --")
my_trader = Robinhood(username="user", password="pw")
print("-------------")

filename = "StocksToBuyTomorrow.csv"
stocks = []
with open(filename) as f:
    for line in f:
        stocks.append([n for n in line.strip().split(',')])
for stock in stocks:
    try:
        x,y = stock[0],stock[1]
        tsymbol = my_trader.instruments(x)[0]
        tsymbol = dict(tsymbol)
       
        for symbol_ in tsymbol:
            if symbol_ == "symbol" and tsymbol[symbol_] != x:
                print(tsymbol[symbol_] + " != " + x)
                break
            else: 
                if symbol_ == "symbol" and tsymbol[symbol_] == x:
                    print(tsymbol[symbol_] + " == " + x)
                    qty = int(y)
                    #buy_order = my_trader.place_buy_order(tsymbol, qty)
                    #print("woulda bought")
                    #sell_order = my_trader.place_sell_order(tsymbol, qty)
                    #print("----")
                    #open(filename, 'w').close()
    except IndexError:
        print ("Well, dang.")
```

**Comment by sanko** [comment]
You're in the wrong place. Check to see what the lib is actually doing behind the scenes.

**Comment by Micah81** [comment]
Ok, sorry about that, and thank you for replying.

**Comment by sanko** [comment]
Without seeing it, I'd assume it's calling [`https://api.robinhood.com/instruments/?query=SB`](https://api.robinhood.com/instruments/?query=SB) which is a keyword search and would return... well, click it and see the first result is Starbucks. What they should be doing is hitting  [`https://api.robinhood.com/instruments/?symbol=SB`](https://api.robinhood.com/instruments/?symbol=SB).

**Comment by Micah81** [comment]
Wow, I believe you solved it.   Here it is, and I'll just change "query" to "symbol".   Thank you so much.
```
    def instruments(self, stock=None):
        res = self.session.get(self.endpoints['instruments'], params={'query':stock.upper()})
        res = res.json()
        return res['results']
```

**Comment by Micah81** [comment]
Yep. I tried stocks SQ and SB and got 
SQ == SQ
woulda bought
SB == SB
woulda bought
