### ISSUE TITLE
Can't figure out historicals

### ISSUE THREAD

**Issue by edasque** [sanko/Robinhood#40]
I know you haven't officially unofficially documented historicals but looking at your perl code, I can't even figure it out. Should this work (but doesn't?):

```
https://api.robinhood.com/quotes/historicals/AAPL/?span=week&interval=day&bounds=regular
```

**Comment by sanko** [comment]
Shouldn't work.

But `https://api.robinhood.com/quotes/historicals/AAPL/?span=week&interval=10minute&bounds=regular` should.

Small datasets are frowned upon. I'll need to take oss a chart up when I get back to documenting everything.

**Comment by edasque** [comment]
Thank you, that did. It was the small dataset thing.
