### ISSUE TITLE
How to get only the most recent orders?

### ISSUE THREAD

**Issue by ige0099** [sanko/Robinhood#41]
Can you give an exact URL example on how to use the  /orders/?updated_at=[gte]&cursor=[$cursor], with the query parameters?
 
I tried few ways to send the query parameter including https://api.robinhood.com/orders/?updated_at[gte]=20170719T165829Z

and 
updated_at=20170719T165829Z

But, it gives all orders without filtering.

**Comment by JeffreyHyer** [comment]
It looks like you need to change the format of your date, it should be: YYYY-MM-DDTHH:MM:SSZ (with dashes and colons).

I've tested it and it's working with the URL formatted like so:
```
https://api.robinhood.com/orders/?updated_at[gte]=2017-07-09T16:58:29Z
```

**Comment by ige0099** [comment]
@JeffreyHyer Thanks for the response. I just missed the dashes and colons! I tried: https://api.robinhood.com/orders/?updated_at[gte]=2017-07-20T14:58:29Z and worked great!

I have one more concern on this: what is the best way to get updates on the orders just placed? Are there any server sent events type of stuffs or do we must have to manually poll?

**Comment by sanko** [comment]
@ige0099 if you have them turned on, push notifications are sent over GCM to registered apps. I'll need to swap a few more questions to get better details than that. Raw instructions soon, maybe.
