### ISSUE TITLE
Adding last trade size and time, and high, low, volume of current trading day

### ISSUE THREAD

**Issue by fimmugit** [sanko/Robinhood#46]
Would it be possible to add last trade size and time to the response?

**Comment by sanko** [comment]
To which response?

**Comment by fimmugit** [comment]
Sorry, forgot to leave the endpoint:

https://api.robinhood.com/quotes/?symbols=MSFT,FB,TSL

Thanks

**Comment by rclai** [comment]
Huh? What last trade size? You mean last trade price?

**Comment by fimmugit** [comment]
I mean the number of shares of the last trade (buy/sell).

**Comment by sanko** [comment]
They've repeatedly asked me to make feature suggestions so I'll add this one to the stack.

**Comment by fimmugit** [comment]
When is this available?

**Comment by rclai** [comment]
I am confused as to what is being requested here. Is this a PR to the /quotes endpoint documentation (which already exists) or is this something else?

**Comment by fimmugit** [comment]
Hi, Richard! Sorry for the confusion. In the quotes/?symbols={xxx,yyy,zzz} API, it returns many fields in which I like to add the last trade's timestamp and the number of shares of that last trade, together with the running volume (i.e. total shares) accumulated from the opening up to the moment of the quotes info being taken.  Hope this clarifies the matter.
