### ISSUE TITLE
OAuth2 push

### ISSUE THREAD

**Issue by sanko** [sanko/Robinhood#47]
Required info:

- [ ] List of scopes
- [ ] Client IDs (hopefully open to 3rd party signups)
- [ ] Complete MFA docs

**Comment by eugv86** [comment]
When should we expect this?

**Comment by sanko** [comment]
@eugv86

Won't do you any good until we're allowed to create secrets for 3rd party apps. Zero chance I'm distributing the official keys.

Reach out to HQ; Baiju is interested in ideas that'll make opening it up worthwhile.

**Comment by lynnwilliam** [comment]
Well I wrote and published an Android app in the play store.
The data was only ever on their phone and it allowed users to download
their Robinhood trade data as a csv file.
There was no 3rd party server involved ,just an app and Robinhood server.

It was very useful for people, to download and analyze their past trades.

Robinhood contacted google, told then I was stealing data and they got my
app pulled from the store and a mark against my developer account.

Than Robinhood also sent me a cease and dissast notice and threatened to
sue me.
So I had to stop using their API all together.

I'm so done with Robinhood, use their API with caution

**Comment by sanko** [comment]
@lynnwilliam

Legal will always do that until they have the go ahead from the board. But they are open to it and the founders intended it to be open a few million accounts ago: https://www.reddit.com/r/RobinHood/comments/7ju90m/ama_with_baiju_bhatt_cofounder_and_coceo_of/dr9b2lp/

**Comment by eugv86** [comment]
Thanks, I reached out a few times already and nothing.... I created a web app for Robinhood so I can track my positions in the browser, turned into something useful for myself at least so I decided to make it public.  Most of the response I got was "I'm not putting my username and password into a 3rd party app"... cant say I blame anyone for that. :)  OAuth would be usefull.  I did open source it for people to use though.  https://github.com/eugv86/Robinhood-Ninja

Thanks again, keep us posted if something changes.

**Comment by sanko** [comment]
Cheap, quick hack until 3rd party OAuth2 support. You'll get a token that is not limited in any way; it's seen as an official client which means it's given an 'internal' scope. But at least this token will expire. Which is something.

https://github.com/sanko/Robinhood/blob/master/Authentication.md#migrate-classic-auth-token-to-oauth2

**Comment by lynnwilliam** [comment]
Is there any talk of a read-only access token ?
Where we can use a token to grant read only access to webcalls that don't
make orders etc.

Users more willing to use third party tools and apps if they know it's read
only.

**Comment by sanko** [comment]
Already exists for supported 3rd parties.

**Comment by lynnwilliam** [comment]
Seams strange they have this all access , do anything API.
But won't give out 3rd party access easily to developers, who want a safe
way to do it.
They are only giving access to 3rd party devs who have a massive user base,
or so I was told.

**Comment by sanko** [comment]
Bother the right people. Drones don't direct the hive.

**Comment by eugv86** [comment]
@sanko Thanks for the update.
