### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by sanko** [sanko/Robinhood#49]
Here we go!

**Comment by zaydek** [comment]
????? :) What's this about?

**Comment by sanko** [comment]
@zaydek Shhhh! 😎

**Comment by zaydek** [comment]
sanko it's live: https://about.robinhood.com/options/#waitlist

**Comment by sanko** [comment]
I have the endpoints. I was told it would be late January so I haven't documented it yet. Busy week for us. AMA on Reddit later today, tv interviews, the whole nine yards.

**Comment by zaydek** [comment]
Wait so do you work at Robinhood now or what? @sanko

**Comment by zbirnba1** [comment]
@sanko do you know when the options endpoints will be documented?  I'd be happy to help.

**Comment by sanko** [comment]
Yes, I do and no thanks.

**Comment by mstrum** [comment]
For anyone interested in the options api ... https://github.com/mstrum/robinhood-python/blob/master/robinhood/RobinhoodClient.py#L2219
