### ISSUE TITLE
Stock Merger

### ISSUE THREAD

**Issue by Denaszune** [sanko/Robinhood#50]
Does Robinhood offer a way to find data on a stock merger? I see a place for stock splits, but I'm pretty sure that data does not include merger data. 

As an example I'm trying to figure out how to calculate what happened to my SCTY shares when they were turned into TSLA shares. But I want to do this dynamically for any merger or any stock.

**Comment by lynnwilliam** [comment]
Look at quandle . They provide that data for a fee.
I pay 390$ for EOD data for nyse and NASDAQ.
They can give you the data you need. Which is the 10k forms and shares
outstanding data.
Than you can calculate the verse splits etc.
Or you can try Edgar online, they provide that data for a fee, but only for
US based companies.

Email me privately at lynnwilliam@gmail.com and I can give you more details.

**Comment by Denaszune** [comment]
Thanks for the information I will need to think about my next steps
