### ISSUE TITLE
Cryptocurrency

### ISSUE THREAD

**Issue by sanko** [sanko/Robinhood#55]
And here we go again...

**Comment by JeffreyHyer** [comment]
Whoa! 😮

**Comment by justinwzig** [comment]
Terrifying

**Comment by lynnwilliam** [comment]
What's terrifying?

**Comment by justinwzig** [comment]
Was being entirely sarcastic :)

**Comment by sanko** [comment]
Join the waitlist: https://crypto.robinhood.com

**Comment by starforever** [comment]
The `/quotes` endpoint doesn't seem to provide support for cryptocurrencies. I'm interested to know what the right endpoint is to do that.

**Comment by imryan** [comment]
Been trying to sniff traffic off my phone using a proxy to get the crypto price endpoints using [mitmproxy](https://mitmproxy.org/), no luck there yet.

**Comment by sanko** [comment]
Crypto runs on a completely different system and requires OAuth (which means 3rd party use will be impossible without being a scumball). It's being documented in a new branch.

**Comment by sanko** [comment]
Actually, I'll test if nummus works with [migrated tokens](https://github.com/sanko/Robinhood/blob/master/Authentication.md#migrate-classic-auth-token-to-oauth2) tomorrow.

**Comment by sanko** [comment]
Yep. They work.

**Comment by bcwik9** [comment]
@sanko were you able to discover the endpoint?

**Comment by sanko** [comment]
The endpoint for...?

**Comment by bcwik9** [comment]
My apologies, I thought you had success in hitting a pricing/quote endpoint for cryptos

**Comment by sanko** [comment]
Yeah. It's going to be in a different branch while I reorganize the entire project.

**Comment by jiezhou0731** [comment]
Hey, are we going to find the endpoint for cryptos quotes in which branch, please?

**Comment by sanko** [comment]
:face_palm:

**Comment by jiezhou0731** [comment]
What do you mean by face palm... I want to find the endpoint to query the cryptos quotes..

**Comment by starforever** [comment]
I think @sanko is working on that. There is a seemly developing version [here](https://github.com/sanko/Robinhood/tree/clarity).

**Comment by jiezhou0731** [comment]
Got you, thanks! @starforever 

Sorry for bugging you. Good works! @sanko
