### ISSUE TITLE
Portfolio Historicals span and interval values

### ISSUE THREAD

**Issue by drew-wallace** [sanko/Robinhood#6]
Any ideas on the different spans and intervals we can ask for?
The following work, but I can't seem to get the month, 3 month, year, and all time to work.
`https://api.robinhood.com/portfolios/historicals/$accountNumber/?span=day&interval=5minute
https://api.robinhood.com/portfolios/historicals/$accountNumber/?span=week&interval=10minute`

**Comment by drew-wallace** [comment]
Nevermind. Found a reference here: https://metacpan.org/pod/Finance::Robinhood#historicals

**Comment by sanko** [comment]
Wow. I never got a notification of this until your reply a few mins ago. Sorry about that. Yeah, I documented it in my Perl module but not here in the API docs... oy, I need to get it together. :)
