### ISSUE TITLE
MFA Failed with Authenticator

### ISSUE THREAD

**Issue by starforever** [sanko/Robinhood#62]
Hi,

I tried this another day. When MFA type was SMS, it worked as expected. However when I changed the MFA type to Google Authenticator (`"mfa_type":"app"`), I received 500 Internal Server Error. Is this because currently API only supports MFA using SMS? If that's really the case maybe we should add this to the doc to keep others aware of this limitation.

Thanks,
Peichao

**Comment by he-zhe** [comment]
I found the MFA API in this [repo](https://github.com/robinhood/deux). But it seems that Google Authenticator has not been added yet. I'm not sure whether other people might have more information on this.

**Comment by eugv86** [comment]
@starforever Getting the same thing with Google Authenticator.
