### ISSUE TITLE
How to access crypto coin quotes?

### ISSUE THREAD

**Issue by bryantharris** [sanko/Robinhood#63]
I know Robinhood now allows crypto coin trading.

In just trying access ticker quote information I tried

curl -v https://api.robinhood.com/quotes/BTC/
curl -v https://api.robinhood.com/quotes/BTC/USD/
curl -v https://api.robinhood.com/quotes/BTC-USD/

Any ideas on how the crypto currencies are mapped in?

**Comment by chiefsmurph** [comment]
I am also wondering about this
