### ISSUE TITLE
Options 

### ISSUE THREAD

**Issue by WaltMit** [sanko/Robinhood#68]
It looks like robinhood gets their data from xignite.com's api. 

Maybe xignite's documentation will help discover how to get detailed quote info from robinhood's api.
https://www.xignite.com/product/global-real-time-option-price-data/#/DeveloperResources/request/GetEquityOption

I am mainly just hoping there is more documentation to come about how to buy and sell options with robinhood's api. Thanks again.

**Comment by sanko** [comment]
This isn't a discovery process. I already have the documentation.

I am given early access to features with the agreement that any documentation or description *follows* the complete release for various reasons. When Options are open for everyone, I'll merge and push the branch. Not before.
