### ISSUE TITLE
What is the request limit to hit the API limitation (Error 429)?

### ISSUE THREAD

**Issue by drew-wallace** [sanko/Robinhood#7]
I got hit with a 429 when accessing historicals for my portfolio. Any ideas when this "ban" will be lifted?

Update: The ban was lifted by the next day

**Comment by chadpriddle** [comment]
I would like to know the request limits. Currently I use etrade API to get quotes of about 80 symbols at a time about every 4-5 seconds.

**Comment by beeedy** [comment]
What is the benefit of using robinhood API for stock quotes when you could use something like yahoo finance or etrade?

**Comment by sanko** [comment]
@beeedy, I'm not sure there is a benifit. In my quant tests, I use better quotes and just trade with RH (with cached instrument IDs).

@chadpriddle, you could use the quote API endpoint to grab them in one call. That'd be one call every 5 seconds... Hardly worthy of a rate limit.

https://api.robinhood.com/quotes/?symbols=MSTF,TSLA,S,MA,F

**Comment by ryho** [comment]
I've been experimenting with the rate limits. I think that you can get away with 1 query per second indefinitely without hitting any limits. At one query every 700ms I still hit a rate limit. For short periods of time you can exceed that limit.
