### ISSUE TITLE
API Error Reporting addition

### ISSUE THREAD

**Issue by inlikefletch** [sanko/Robinhood#9]
Hi,
Awesome work here! This has been a very helpful repo! One thing I learned that you may want to add to the API Error Reporting page:

HTTP Error 405: Method Not Allowed: HTTPError
post or get

I learned that when doing a cancel request with python urllib2 request, i.e.
urllib2.Request('https://api.robinhood.com/orders/1234567890/cancel/')
I would have to change it to:
urllib2.Request('https://api.robinhood.com/orders/1234567890/cancel/','')

Appending the empty data parameter forces the request as a POST vs a GET

Jason

**Comment by sanko** [comment]
Easy to overlook but cancel does require an HTTP POST [as documented](https://github.com/sanko/Robinhood/blob/master/Order.md#cancel-an-order).
